export const AUTH_COPY = {
  eyebrow: "Hesap",
  title: "Giriş yap veya kayıt ol.",
  description: "Hesabınla devam et ya da yeni hesap oluştur.",
  publisherHeroEyebrow: "Yayıncı hesabı",
  publisherHeroTitle: "Yayıncı hesabın",
  settingsEyebrow: "Hesap ayarları",
  settingsTitle: "Kullanıcı adını güncelle",
  settingsDescription: "Kullanıcı adını buradan güncelleyebilirsin.",
  settingsInfoBody:
    "E-posta ve şifre bu turda değiştirilemez.",
  settingsEmailLabel: "E-posta",
  settingsRoleLabel: "Rol",
  settingsAccountStatusLabel: "Hesap durumu",
  settingsRoleUserLabel: "Kullanıcı",
  settingsRolePublisherLabel: "Yayıncı",
  settingsRoleAdminLabel: "Admin",
  settingsAccountStatusActiveLabel: "Aktif",
  settingsMetaTitle: "Kayıtlı bilgiler",
  settingsNavLabel: "Ayarlar",
  settingsUsernameFormTitle: "Yeni kullanıcı adı",
  settingsUsernameFormDescription:
    "Kullanıcı adın 3 ile 24 karakter arasında olmalı.",
  settingsCurrentUsernameLabel: "Mevcut kullanıcı adı:",
  settingsUsernameInputLabel: "Yeni kullanıcı adı",
  settingsUsernameHelp:
    "Yalnız küçük harf, rakam, nokta, tire ve alt tire kullanabilirsin.",
  settingsUsernameSubmitLabel: "Güncelle",
  settingsUsernameSubmitPendingLabel: "Kullanıcı adı kaydediliyor",
  settingsUsernameErrorTitle: "Kullanıcı adı güncellenemedi",
  settingsUsernameSuccessTitle: "Kullanıcı adı güncellendi",
  settingsUsernameSuccessBody: "Yeni kullanıcı adın hesabına kaydedildi.",
  settingsUsernameSuccessInlineLabel: "Güncellendi",
  settingsUsernameSameValueBody: "Yeni bir kullanıcı adı gir.",
  settingsBackLabel: "Hesabıma dön",
  loginTitle: "Giriş yap",
  loginDescription: "Kullanıcı adın veya e-postanla giriş yap.",
  userRegisterTitle: "Kullanıcı hesabı oluştur",
  userRegisterDescription: "Yeni kullanıcı hesabını kısa bir form ile oluştur.",
  publisherRegisterTitle: "Yayıncı hesabı oluştur",
  publisherRegisterDescription: "Başvurunu tek formda tamamla.",
  publisherSessionLabel: "Açık hesap",
  sessionTitle: "Hesabım",
  sessionDescription: "",
  sessionActiveBody: "Bu cihazda hesabın açık.",
  publisherPendingContinuityTitle: "Başvurun alındı",
  publisherPendingTitle: "Başvurun alındı",
  publisherPendingBody:
    "İnceleme tamamlanana kadar bekleyebilir ve keşiften devam edebilirsin.",
  publisherPendingSupportTitle: "Destek",
  publisherPendingSupportBody:
    "İnceleme uzarsa kayıt bilgilerinle destek ekibine başvurabilirsin.",
  publisherApprovedTitle: "Onay hazır",
  publisherApprovedBody: "Yayın açma iznin aktif.",
  publisherRejectedTitle: "Başvurun kabul edilmedi",
  publisherRejectedBody:
    "Yayın açma izni şu anda açılmadı. Bu aşamada yeniden başvuru gönderemezsin.",
  publisherRejectedSupportTitle: "Destek",
  publisherRejectedSupportBody:
    "Kayıt bilgilerinle destek ekibine başvurarak durumunu paylaşabilirsin.",
  publisherFallbackTitle: "Başvuru durumu şu anda gösterilemiyor",
  publisherMissingBody:
    "Başvuru kaydın henüz doğrulanamıyor. Şimdilik keşiften devam edebilirsin.",
  publisherDegradedBody:
    "Başvuru durumun şu anda okunamıyor. Daha sonra tekrar deneyebilirsin.",
  publisherCoverPanelTitle: "Kapak seçimi",
  publisherCoverPanelDescription: "Hazır kapaklardan birini seç.",
  publisherCoverEmptySelectedTitle: "Kapak seçilmedi",
  publisherCoverEmptySelectedBody: "Henüz kapak seçilmedi.",
  publisherCoverDegradedTitle: "Kapak kataloğu şu anda açılamıyor",
  publisherCoverDegradedBody: "Daha sonra tekrar deneyebilirsin.",
  publisherCoverChooseLabel: "Kapak olarak seç",
  publisherCoverChoosePendingLabel: "Kaydediliyor",
  publisherCoverOpenSheetLabel: "Kapak seç",
  publisherCoverSheetTitle: "Kapak seç",
  publisherCoverSheetCloseLabel: "Kapak seçim yüzeyini kapat",
  publisherCoverSelectedLabel: "Seçili",
  publisherCoverSelectedBody: "Bu kapak hesabında aktif görünüyor.",
  publisherCoverSaveErrorTitle: "Kapak kaydedilemedi",
  publisherCoverUnauthorizedBody:
    "Kapak seçimi yapmak için yayıncı hesabınla giriş yapman gerekiyor.",
  publisherCoverInvalidBody:
    "Seçtiğin kapak şu anda doğrulanamıyor. Listeyi yenileyip tekrar dene.",
  publisherCoverDataAnomalyBody:
    "Kapak ayarın şu anda güvenli biçimde güncellenemiyor. Destekle paylaşılacak veri tutarsızlığı var.",
  publisherCoverUnavailableBody:
    "Kapak seçimi şu anda kaydedilemiyor. Daha sonra tekrar deneyebilirsin.",
  adminApprovalTitle: "Yayıncı başvuruları",
  adminApprovalBody: "Başvuruları buradan incele.",
  adminFilterPendingLabel: "Bekleyen",
  adminFilterApprovedLabel: "Onaylanan",
  adminFilterRejectedLabel: "Reddedilen",
  adminFilterAllLabel: "Tümü",
  adminApprovalEmptyTitle: "Bekleyen başvuru yok",
  adminApprovalEmptyBody: "İşlem bekleyen başvuru görünmüyor.",
  adminApprovalApprovedEmptyTitle: "Onaylanan başvuru yok",
  adminApprovalApprovedEmptyBody: "Onaylanmış başvuru görünmüyor.",
  adminApprovalRejectedEmptyTitle: "Reddedilen başvuru yok",
  adminApprovalRejectedEmptyBody: "Reddedilmiş başvuru görünmüyor.",
  adminApprovalAllEmptyTitle: "Başvuru görünmüyor",
  adminApprovalAllEmptyBody: "Listelenecek başvuru görünmüyor.",
  adminApprovalDegradedTitle: "Başvuru kuyruğu açılamıyor",
  adminApprovalDegradedBody: "Başvurular şu anda okunamıyor. Daha sonra tekrar dene.",
  adminApproveLabel: "Onayla",
  adminRejectLabel: "Reddet",
  adminStatusPendingLabel: "Beklemede",
  adminStatusApprovedLabel: "Onaylandı",
  adminStatusRejectedLabel: "Reddedildi",
  adminApproveSuccessLabel: "Onay bekleyen başvuru",
  adminReviewMetaPrefix: "Başvuru tarihi",
  adminApproveErrorBody:
    "Bu başvuru şu anda işlenemiyor. Listeyi yenileyip tekrar dene.",
  continueLabel: "Devam et",
  returnDiscoveryLabel: "Keşfe dön",
  goStudioLabel: "Stüdyoya git",
  signOutLabel: "Çıkış yap",
  signInLabel: "Giriş yap",
  userRegisterLabel: "Kullanıcı hesabı oluştur",
  publisherRegisterLabel: "Yayıncı başvurusunu tamamla",
  loginToggle: "Giriş",
  userRegisterToggle: "Kullanıcı kaydı",
  publisherRegisterToggle: "Yayıncı kaydı",
  fullNameLabel: "Ad soyad",
  phoneLabel: "Telefon",
  identifierLabel: "E-posta veya kullanıcı adı",
  emailLabel: "E-posta",
  usernameLabel: "Kullanıcı adı",
  passwordLabel: "Şifre"
} as const;
